#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May  3 18:56:24 2023

@author: dhvilleg
"""

import cv2
import numpy as np

bananos = cv2.imread('/home/dhvilleg/Documents/proyectos/DeepVision/duen.jpg')

gray = cv2.cvtColor(bananos,cv2.COLOR_BGRA2GRAY)

gx = cv2.Sobel(gray, cv2.CV_64F, 1, 0, 5)
gy = cv2.Sobel(gray, cv2.CV_64F, 0, 1, 5)

mag, ang = cv2.cartToPolar(gx, gy)


cv2.imshow("sin escalar",mag)
cv2.waitKey(0)
cv2.destroyAllWindows()

mag = np.uint8(255 * mag / np.max(mag))

cv2.imshow("escalado",mag)
cv2.waitKey(0)
cv2.destroyAllWindows()
